### PR TITLE
 take()取值不可能为空，不需要做判空处理

### PR DESCRIPTION
**Pull request by klboke**

### CODE REVIEW

**Comment by gosonzhang** [comment]
thanks for your contribution @klboke !

The log4j's configure files are packaged by assembly.xml, not need add extra files.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

log4j的配置文件由assembly.xml打包，不需要添加额外的文件

**Comment by klboke** [comment]
在IDEA开发调试时，直接main方法启动，加载不到日志文件，也没有定义输出到控制台的日志，非常不方便开发调试

**Review by tisonkun — CHANGES_REQUESTED** [review]
Thanks for your contribution @klboke!

I think here you propose two topic. One is the redundant null checker, the other is log4j.properties. You can separated them into two pull request so that one wouldn't block the other. Besides, log4j.properties contains non-UTF-8 character that should not be checked into our repository.

**Comment by klboke** [comment]
I feel that adding a log to the console here helps with debugging during development. I deleted it first. This topic can be discussed in another pr.

***
我觉得在这里添加打印到控制台的日志，有助于开发时调试，这里先删掉了，这个话题可以在另一个pr中讨论

**Review by tisonkun — APPROVED** [review]
Thanks for your update. The change looks good to me.

**Comment by gosonzhang** [comment]
thanks

**Pull request merged**
