### PR TITLE
Add Javadocs

### PR DESCRIPTION
**Pull request by kennethvt437**
Adding javadocs to these interface methods would help clarify what they are supposed to do

### CODE REVIEW

**Comment by tisonkun** [comment]
Hi @kennethvt437. Thanks for your contribution!

I think it also makes sense we introduce a checkstyle rules to enforce every interface methods have a proper javadoc. But back to this pull request I don't think it provides extra benefit we just place a dummy document. In fact, it is even worse, since it possibly passes checker that enforces a javadoc but the document is dummy and thus meaningless.

**Comment by tisonkun** [comment]
Briefly, could you update the pull request to replace dummy doc with meaningful javadoc?

**Comment by kennethvt437** [comment]
I was hoping the person who wrote the methods could add meaningful content to the javadocs, since I can't really tell what the methods do or the parameters mean just from this file.

**Comment by tisonkun** [comment]
@kennethvt437 if so, maybe it is better to open an issue instead of open a dummy pull request. What do you think?

**Comment by kennethvt437** [comment]
Oh, okay. Next time if I see something like this I'll open an issue

**Comment by tisonkun** [comment]
Could you please then close this one?

**Pull request closed without merging**
