### PR TITLE
[hotfix] format annotation

### PR DESCRIPTION
**Pull request by aloyszhang**
this is a hotfix. 
format annotation in `DefaultBdbStoreService`

### CODE REVIEW

**Comment by aloyszhang** [comment]
cc @gosonzhang

**Review by tisonkun — CHANGES_REQUESTED** [review]
Thanks for your contribution @aloyszhang. The change LGTM.

However, I'm thinking of whether we can widen this pull request to fully check our codebase and get rid of unformatted comment? Maybe we can introduce an automatic tools.

To be clear, I am trying to make style only changes into once patch instead of many minor patches so that prevent our commit logs from polluted.

**Review by gosonzhang — APPROVED** [review]

**Review by tisonkun — COMMENTED** [review]
Nevertheless, my comments above should not be a blocker. This patch itself is good to go.

**Comment by gosonzhang** [comment]
@TisonKun, for these residual code style problems, timely modification is also a better way to deal with them.

**Review by tisonkun — APPROVED** [review]
Thanks for the explanation @gosonzhang. Fair enough to go ahead.

**Pull request merged**
