### PR TITLE
Replace sun reference with apache commons

### PR DESCRIPTION
**Pull request by ctide**
Replace reference to sun.misc.BASE64Encoder with org.apache.commons.code.binary.Base64

### CODE REVIEW

**Review by gosonzhang — COMMENTED** [review]
Hi Chris, can you make this change work in a Java 7 environment?

**Comment by ctide** [comment]
Is this not working for you in Java 7? This should be a Java 7 compatible change.

**Comment by tisonkun** [comment]
Related to #69 

I think since it use apache-common instead of Java 8 `Base64` it is Java 1.7 compatible. @ctide could you share a gist checking that two-way codec are compatible? It would be like https://github.com/Tencent/TubeMQ/pull/70#issuecomment-540014908

**Comment by ctide** [comment]
https://gist.github.com/ctide/fd516723790d365952c64ac06fce43ee just updating the one in the other comment to use apache commons instead works. I wouldn't want to add the test itself to the project because then you have to bring in the sun libs.

**Review by gosonzhang — APPROVED** [review]
I verified that it is supported in Java 7, thank you!

**Comment by gosonzhang** [comment]
thanks @ctide

**Pull request merged**
