### PR TITLE
Generate TubeClientVersion.java and TubeServerVersion.java automatically

### PR DESCRIPTION
**Pull request by guangxuCheng**
TubeClientVersion.java and TubeServerVersion.java save the version information for TubeMQ which should be consistent with the project version. Maybe it is a better choice to generate these two files based on project version number automatically.

@gosonzhang can you take a look? thanks

### CODE REVIEW

**Comment by gosonzhang** [comment]
Need to supplement the test under windows environment

－－－－－－－－－－－－－－－

需要补充windows环境下的测试

**Comment by guangxuCheng** [comment]
Update patch to support compiling project in windows environment.

**Comment by tisonkun** [comment]
Close and reopen to trigger travis.

**Comment by guangxuCheng** [comment]
> Need to supplement the test under windows environment
> 
> －－－－－－－－－－－－－－－
> 
> 需要补充windows环境下的测试

As @gosonzhang  suggestions ，TubeMQ should also be built correctly in Windows environment. 
So, should we update .travis.yml to make Travis CI test for Linux, OS X, Windows ? @TisonKun @yiheng

**Comment by tisonkun** [comment]
@guangxuCheng AFAIK travis doesn't provide standard Windows support. See also [this page](https://docs.travis-ci.com/user/reference/windows/).

For now it seems we have to test manually and react to issues reported specific to windows. Maybe migrate to Jenkins is another option but I have no idea how it should go.

**Comment by yiheng** [comment]
I have no experience of this through Travis. For now, maybe open a ticket to track this.

**Comment by gosonzhang** [comment]
Ok, I'll check and merge, thanks.

**Comment by gosonzhang** [comment]
thanks

**Pull request merged**
