### PR TITLE
Issue 8: Add issue templates

### PR DESCRIPTION
**Pull request by tisonkun**
Visual results with this patch

issue-template-0
issue-template-1
issue-template-2
issue-template-3

You can also try it out by creating issues in https://github.com/TisonKun/TubeMQ ([issues](https://github.com/TisonKun/TubeMQ/issues) -> [New Issue](https://github.com/TisonKun/TubeMQ/issues/new/choose))

### CODE REVIEW

**Comment by tisonkun** [comment]
@gosonzhang @yiheng @guangxuCheng Could you take a look?

**Comment by guangxuCheng** [comment]
lgtm

**Comment by tisonkun** [comment]
Thanks for your review @guangxuCheng! I don't have write access to the repo so it would be helpful if you help to merge it.

Besides, I am not sure whether the format "Issue 8: ..." is ok. But before a standard output from #15 all readable format should be valid.

**Comment by yiheng** [comment]
This looks great. Only one concern, have we decided to use github issues to manage our tickets?

**Comment by tisonkun** [comment]
@yiheng At least RocketMQ adopts GitHub issue as issue tracker so I think it wouldn't be a blocker that we use GitHub issue as issue tracker.

I agree that it is an open issue which issue tracker we finally adopt. But it wouldn't block this pull request that we make current state a bit better.

**Pull request merged**
