### PR TITLE
Fix bugs for admin_mod_group_filtercond_info and admin_bath_add_group_filtercond_info

### PR DESCRIPTION
**Pull request by gosonzhang**

### CODE REVIEW

**Review by lizhiboo — APPROVED** [review]

**Review by tisonkun — COMMENTED** [review]
Thanks for opening this pull request @gosonzhang . Could you please provide description & update commit content for the motivation for this change and what it does? It would be helpful so that we don't lost context here if we refer to it later.

---

能麻烦 goson 更新 PR 的描述和 commit 的描述里关于这个改动的动机和改法吗？

**Comment by gosonzhang** [comment]
bugs

**Comment by gosonzhang** [comment]
filterConds content must be extracted from filterCondJsonSet

**Comment by tisonkun** [comment]
Thanks for your information

**Pull request merged**
