### PR TITLE
#76 [Configuration] Add description information for BDB-JE replication group

### PR DESCRIPTION
**Pull request by aloyszhang**
Add description information for BDB-JE replication group

### CODE REVIEW

**Comment by aloyszhang** [comment]
CC @gosonzhang

**Review by gosonzhang — COMMENTED** [review]
Can you add comment for bdbReplicaSync?

**Comment by aloyszhang** [comment]
Thanks for your reply @gosonzhang ,  I have add detail description for `bdbLocalSync and` `bdbReplicaSync` in mater.ini

**Review by gosonzhang — APPROVED** [review]

**Comment by gosonzhang** [comment]
Thanks for your contribution!

**Pull request merged**
